### ISSUE TITLE
If customer says "No" to "Is this the spouse?", "What's your name?" should play

### ISSUE THREAD

**Issue by NicksAccount** [LCN-Dev/GoogleBot#118]
#### Brief description of the issue:
When a customer picks up and it is not the right person or the spouse, the clip "What's your name?" should play. This could possibly turn normal quick dispos into leads. 
#### What happened?:
Customer isn't the right person or the spouse. 
#### What _should_ have happened?:
"What is your name?"...thus possibly producing a lead if the person goes through and answers the questions. 
#### Steps to reproduce:
Add clip into code. Also, make the birthday set to nothing if this person isn't the spouse, but chooses to go on with the call. This way Cheryl doesn't ask the person if the birthday she has is correct, because it won't be correct as this customer just made it clear to Cheryl it wasn't the right person or the spouse.
#### Additional info:
 - **Bot Revision**: Found under the hidden folder /.git/packed-refs, which you open with notepad and copy the second line of text to paste here.
 - **Anything else you may wish to add**: (Related issues, console output, error notices, screenshots, etc.)

**Comment by NicksAccount** [comment]
Either I can't find where to put a tag on this, or it's not letting me. 
My apologies.

**Comment by SpadesNeil** [comment]
I usually handle tagging, no worries.

**Comment by MTS11648** [comment]
This would be a really neat feature, unless someone else gets to it first, I will probably work on this later on in the day.

**Comment by MTS11648** [comment]
Please see #123.

**Comment by SpadesNeil** [comment]
Actually this should already be handled in the code elsewhere. Marking this as invalid.
