### ISSUE TITLE
Cheryl often misinterprets negative responses to the TCPA as positive.

### ISSUE THREAD

**Issue by MTS11648** [LCN-Dev/GoogleBot#119]
#### Brief description of the issue:
Customer will say something like "That is **NOT** okay with me!" to the TCPA and Cheryl will still wish them luck on the quotes.
#### What happened?:
Exactly what's mentioned above.
#### What _should_ have happened?:
Cheryl should use her infamous TCPA rebuttal instead of pretending they consented.
#### Steps to reproduce:
1. Go through the call normally.
2. Say something along the lines of "That isn't okay with me!" at the TCPA.
3. Watch Cheryl interpret your clearly negative answer as a positive one.
#### Additional info:
This is annoying because if Cheryl hears a positive answer she will post the lead to the lead-getter. That means if we're running behind on leads, we have to waste time listening to a call that isn't a lead in the first place. More importantly, if we ever do improve our automation, Cheryl may submit a lead despite the customer not giving their consent. You could probably fix this by starting the Cheryl rebuttal if the response contains "no" (as that will catch _not_ as well).

**Comment by SpadesNeil** [comment]
Ew yea I have seen this happen a few times.

**Comment by SpadesNeil** [comment]
Bumping down to minor since this really just annoys the lead entry people.

**Comment by SpadesNeil** [comment]
Haven't seen this in a while.
