### ISSUE TITLE
"I just started the policy this month" Could eliminate the "How many years have you been with them?" question. 

### ISSUE THREAD

**Issue by NicksAccount** [LCN-Dev/GoogleBot#120]
#### Brief description of the issue:
When someone answers the "When is your policy going to expire?" question with "(something)...I just started it this month, anyways", it could totally take away the "How many years have you been with them?" question. 
#### What happened?:
Someone states "I just got with them this month" to initial insurance question
#### What _should_ have happened?:
Skip the question involving how long they've been with them. We already know this info.
#### Steps to reproduce:
Find "Just started this month" in speech to policy expiration question. Skip question involving how long they've had the policy.
#### Additional info:
 - **Bot Revision**: https://github.com/LCN-Dev/GoogleBot/commit/7cae7e2d262a7505144b4289853658560d0648f2

**Comment by SpadesNeil** [comment]
I got this mang.
