### ISSUE TITLE
Cheryl rushes through questions sometimes

### ISSUE THREAD

**Issue by SpadesNeil** [LCN-Dev/GoogleBot#131]
#### Brief description of the issue:
On occasion, seemingly without reason (but as programmers we know that isn't true), Cheryl likes to rush through questions at too quickly of a pace, cutting off the customer before they can finish talking.

I'm not sure what causes this bug, but it has existed in the code since I first started working here. It doesn't happen often, but when it does, it screws up the call sometimes.

#### What happened?:
See above.

#### What _should_ have happened?:
Also see above. Cheryl needs to at least give a moment for the silence timer to play after each question. However there also needs to be a check if the person rambles on about nonsense, so a timer to cut them off would also be nice.

#### Steps to reproduce:
Unknown.

#### Additional info:
 - **Bot Revision**: https://github.com/LCN-Dev/GoogleBot/commit/832ed5182cc38ddb7d404b63b1cfb729f54b0a80
 - **Anything else you may wish to add**: I propose making sure we have a working cooldown time between questions. During that time we'll still take in audio to strings, but we won't send it through the functions until the cooldown expires. I'd swear that there _should_ be something like that already, but if there's not, there should be.

**Comment by MTS11648** [comment]
This is happening a lot more than it used to, maybe one of our recent additions messed something up?

**Comment by SpadesNeil** [comment]
Bumping this up to severe. Funny thing is, by fixing other parts of the code to make it run better and faster, we likely have inadvertently highlighted an older problem.

This can probably be fixed by checking the silence timer before moving on to the next question.

**Comment by SpadesNeil** [comment]
This seems to be an issue with the silence timer. I don't think it's fixed entirely, but it's definitely alleviated. Marked as resolved for now.
