### ISSUE TITLE
Instead of asking "How many vehicles...?", ask "What is the vehicle you have on your policy?"

### ISSUE THREAD

**Issue by NicksAccount** [LCN-Dev/GoogleBot#137]
#### Brief description of the issue:
I have been listening to calls of real life Cheryl. She rarely, if ever, asks "how many vehicles do you have?", instead, in a MUCH friendlier voice, she says; "What is the vehicle on your policy?"
#### What happened?:
Cheryl has a much more effective question for this that also sounds a lot better than the current. It also shortens the call by cutting away a question. 
#### What _should_ have happened?:
Cheryl should ask "What is the vehicle on your policy?", if someone says "I have two.", that could open up the question; "Can I have the year make and model of the first vehicle?", but if the customer goes along with Cheryl's original question, we won't have to ask for the first, second, or third vehicle. Thus cleaning up that question. 
#### Steps to reproduce:
Add new audio file
Make it so when customer says, "I have more than 1 vehicle" or anything along those lines, it will ask for the YM&M of the first, and so on. If not, they will answer with their YM&M and Cheryl will not have to ask how many vehicles they have. Cutting about 10 seconds off the call.
#### Additional info:
 - **Bot Revision**: Found under the hidden folder /.git/packed-refs, which you open with notepad and copy the second line of text to paste here.
 - **Anything else you may wish to add**: (Related issues, console output, error notices, screenshots, etc.)

**Comment by SpadesNeil** [comment]
Adding "needs audio file" even though you said the clip exists already because I might want to add in a few other changes to how this part of the call is handled.

"HOWMANYVEHICLESDOYOUHAVE?!" always felt really harsh to me.

**Comment by NicksAccount** [comment]
I have the audio clip for this

**Comment by SpadesNeil** [comment]
Oh, okay, then! I misunderstood.

**Comment by NicksAccount** [comment]
The soundfile will be in Desktop > YMMYV.mp3

**Comment by SpadesNeil** [comment]
My only concern is that this could get confusing when Cheryl asks this question. Coding solutions for this might cause more problems than ten more seconds resolves. It'd probably be beneficial for Cheryl to ask "How many vehicles are on your policy?" rather than bluntly, "How many vehicles do you have?" as I have occasionally noticed some callers rattle on about vehicles they don't drive.

Bumping this issue down to minor, also, since the more I think about it, the less I'm sure how much difference this would make. It's worth a test anyway.

**Comment by NicksAccount** [comment]
We should take this out, because regardless if Cheryl says "What's the year make and model of your first vehicle?" or "What's the year make and model of your vehicle?" people will give both or just one, depending on what they have.

**Comment by SpadesNeil** [comment]
https://github.com/LCN-Dev/GoogleBot/pull/235 is relevant to this.
