### ISSUE TITLE
Overhaul of the "YMM" Question

### ISSUE THREAD

**Issue by MTS11648** [LCN-Dev/GoogleBot#140]
#### Brief description of the issue:
Most of the time when people have more than one vehicle, they just say all of them rapidly; it is pointless for Cheryl to ask the YMM of the vehicles individually.
#### What happened?:
N/A
#### What _should_ have happened?:
Cheryl should say something along the lines of, "And the year makes and models of those vehicles?" if the customer has more than one.
#### Steps to reproduce:
1) Get to YMM question.
2) Say you have two vehicles.
3) Tell Cheryl both vehicles at the same time.
4) Watch as she pointlessly asks for the second vehicle YMM again, wasting time.

**Comment by SpadesNeil** [comment]
Fortunately, our existing audio clip, "And may I have the year, make, and model of your vehicle?" sounds like "vehicle*s*" over the phone, so this is a very small change.

"What are the year, make, and model of those vehicles?" is probably a better way to word it, but we need to try to be careful and avoid Cheryl cutting people off.

Also should maybe change the prior question "How many vehicles do you have?" to "How many vehicles are on your policy?" but I'd want to talk to Justin or Leo before doing that.

**Comment by MTS11648** [comment]
You are definitely right about it sounding like she is saying "vehicles" in the clip we already have, but the main issue I see here is when she goes through her whole shpeel of "What is the year make and model of the first vehicle?" then "What is the year make and model of the second vehicle?" for absolutely no reason.

**Comment by SpadesNeil** [comment]
I see what you mean.

**Comment by SpadesNeil** [comment]
We're abandoning the "How many vehicles do you have?" question, rendering this issue moot.
