### ISSUE TITLE
"I don't have a car" "I do not have a car" heard, still goes on

### ISSUE THREAD

**Issue by NicksAccount** [LCN-Dev/GoogleBot#154]
#### Brief description of the issue:
Customer says "I don't have a car", Cheryl proceeds with the phonecall.
Customer says "I do not have a car" and Cheryl still went on
(This was the same call)
#### What happened?:
^^^^^^
#### What _should_ have happened?:
Call should have been dispositioned as "no car" 
#### Steps to reproduce:
Add "I don't have a car" to vocabulary for no car dispo. 
#### Additional info:
 - **Bot Revision**: Found under the hidden folder /.git/packed-refs, which you open with notepad and copy the second line of text to paste here.
 - **Anything else you may wish to add**: (Related issues, console output, error notices, screenshots, etc.)

**Comment by SpadesNeil** [comment]
Could be misheard phrases.

**Comment by SpadesNeil** [comment]
Can't find this. Re-open if it appears again.
