### ISSUE TITLE
New Voice How-To

### ISSUE THREAD

**Issue by MTS11648** [LCN-Dev/GoogleBot#157]
We should:
1) Modify the "Conversation.RollTheClip" function to incorporate some sort of try-catch in order to avoid missing sound clip errors.
2) Comment out the parts of the code that have Cheryl say birthdates and names.
3) To be continued...

**Comment by SpadesNeil** [comment]
There's still a lot of straight up missing audio which we need to do a good lead but changing the RollTheClip function to catch missing sounds and not cease functioning would make this process faster toward getting a workable prototype.
