### ISSUE TITLE
The Don Bot audio

### ISSUE THREAD

**Issue by SpadesNeil** [LCN-Dev/GoogleBot#159]
#### Brief description of the issue:
The following files must be recorded before The Don Bot can be functional.

We have some of these already, they just need to be sorted. Some of them we do have aren't good for the bot for whatever reason.

- [x] C:\SoundBoard\Don\DRIVER INFO\Marital Status.mp3
- [ ] C:\SoundBoard\Don\DRIVER INFO\Spouses Date of Birth.mp3
- [ ] C:\SoundBoard\Don\DRIVER INFO\Spouses First name.mp3
- [x] C:\SoundBoard\Don\DRIVER INFO\military.mp3
- [ ] C:\SoundBoard\Don\DRIVER INFO\spouse military.mp3
- [x] C:\SoundBoard\Don\INSURANCE INFO\EXPIRATION.mp3
- [ ] C:\SoundBoard\Don\INSURANCE INFO\Ins provider 1.mp3
- [ ] C:\SoundBoard\Don\INSURANCE INFO\Ins provider 2.mp3
- [ ] C:\SoundBoard\Don\INSURANCE INFO\Ins provider 3.mp3
- [x] C:\SoundBoard\Don\INSURANCE INFO\Policy EXP 1.mp3
- [x] C:\SoundBoard\Don\INSURANCE INFO\Policy EXP 2.mp3
- [ ] C:\SoundBoard\Don\INSURANCE INFO\WHODOYOUUSE.mp3
- [x] C:\SoundBoard\Don\INSURANCE INFO\Years with 1.mp3
- [ ] C:\SoundBoard\Don\INSURANCE INFO\Years with 2.mp3
- [ ] C:\SoundBoard\Don\INSURANCE INFO\Years with 3.mp3
- [ ] C:\SoundBoard\Don\INTRO\HELLO.mp3
- [ ] C:\SoundBoard\Don\INTRO\INTROREPEAT.mp3
- [ ] C:\SoundBoard\Don\INTRO\THISISTOGIVENEWQUOTE.mp3
- [ ] C:\SoundBoard\Don\INTRO\hello 1.mp3
- [ ] C:\SoundBoard\Don\INTRO\hello 2.mp3
- [ ] C:\SoundBoard\Don\INTRO\hello.mp3
- [x] C:\SoundBoard\Don\PERSONAL INFO\Credit.mp3
- [ ] C:\SoundBoard\Don\PERSONAL INFO\Do You Own Or Rent the Home.mp3
- [x] C:\SoundBoard\Don\PERSONAL INFO\EMAIL.mp3
- [x] C:\SoundBoard\Don\PERSONAL INFO\HOMETYPE.mp3
- [ ] C:\SoundBoard\Don\PERSONAL INFO\I would just need an email address that you have access to.mp3
- [ ] C:\SoundBoard\Don\PERSONAL INFO\Last Name.mp3
- [ ] C:\SoundBoard\Don\PERSONAL INFO\MOBILECARRIER.mp3
- [ ] C:\SoundBoard\Don\PERSONAL INFO\PHONETYPE.mp3
- [ ] C:\SoundBoard\Don\PERSONAL INFO\and your email is still.mp3
- [ ] C:\SoundBoard\Don\PUSHONS\allstategeicostatefarm.mp3
- [ ] C:\SoundBoard\Don\PUSHONS\chevyfordgmc.mp3
- [ ] C:\SoundBoard\Don\REACTIONS\Can you repeat that.mp3
- [x] C:\SoundBoard\Don\REACTIONS\Could you please verify your address.mp3
- [ ] C:\SoundBoard\Don\REACTIONS\Excellent 2.mp3
- [ ] C:\SoundBoard\Don\REACTIONS\Hello 4.mp3
- [ ] C:\SoundBoard\Don\REACTIONS\No.mp3
- [ ] C:\SoundBoard\Don\REACTIONS\OTAGC.mp3"
- [ ] C:\SoundBoard\Don\REACTIONS\Thank you.mp3
- [ ] C:\SoundBoard\Don\REACTIONS\VeryGood.mp3
- [ ] C:\SoundBoard\Don\REACTIONS\Yes.mp3
- [ ] C:\SoundBoard\Don\REACTIONS\You're-welcome.mp3
- [ ] C:\SoundBoard\Don\REACTIONS\can you repeat that 1.mp3
- [ ] C:\SoundBoard\Don\REACTIONS\can you repeat that 2.mp3
- [ ] C:\SoundBoard\Don\REACTIONS\can you repeat that 3.mp3
- [ ] C:\SoundBoard\Don\REACTIONS\can you repeat that 4.mp3
- [ ] C:\SoundBoard\Don\REACTIONS\can you repeat that.mp3
- [ ] C:\SoundBoard\Don\REACTIONS\yeah 1.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\Address Rebuttal.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\Can They Email.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\Can You Just Verify the month.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\DNC.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\Email Rebuttal 2.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\Email Rebuttal.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\HappyWithInsurance.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\I already have insurance rebuttal.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\I completely understand.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\I'm required to have you verify it first.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\IllBeAbout20Seconds.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\Is This the Spouse.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\January feb march april.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\Let me Just confirm a few things.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\Local agents and carriers in your area.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\My spouse takes care of that.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\NotThatCheap.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\P.O Box rebuttal.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\REBUTTAL3.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\Rebuttal1.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\Sorry to Hear That 2.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\That's a great AutoFormQuestion.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\That's okay.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\This Will be Real quick.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\This info.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\ThisIsJustAQuickProccess.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\What was your name 3.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\What's LCN.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\When will they call.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\Why do you need my info.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\Will I get many calls.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\You're not giving me a quote.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\nothing to be interested in.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\scam rebuttal.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\sorry.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\this info.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\we're almost done.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\where did you get my info.mp3
- [ ] C:\SoundBoard\Don\REBUTTALS\which address rebuttal.mp3
- [ ] C:\SoundBoard\Don\TIE INS\Could You Please Spell That Out.mp3
- [ ] C:\SoundBoard\Don\TIE INS\Great What's Your Best Guess.mp3
- [ ] C:\SoundBoard\Don\VEHICLE INFO\2nd Vehicle.mp3
- [ ] C:\SoundBoard\Don\VEHICLE INFO\First Vehicle.mp3
- [ ] C:\SoundBoard\Don\VEHICLE INFO\Fourth Vehicle.mp3
- [ ] C:\SoundBoard\Don\VEHICLE INFO\How many vehicles do you have.mp3
- [ ] C:\SoundBoard\Don\VEHICLE INFO\Third Vehicle.mp3
- [x] C:\SoundBoard\Don\VEHICLE INFO\YMMYV.mp3
- [ ] C:\SoundBoard\Don\WRAPUP\ENDCALL.mp3
- [x] C:\SoundBoard\Don\WRAPUP\Have a great day.mp3
- [ ] C:\SoundBoard\Don\WRAPUP\PPCoverage.mp3
- [ ] C:\SoundBoard\Don\WRAPUP\Square footage.mp3
- [x] C:\SoundBoard\Don\WRAPUP\TCPA.mp3
- [ ] C:\SoundBoard\Don\WRAPUP\TCPAREBUT.mp3
- [ ] C:\SoundBoard\Don\WRAPUP\Which secondaries.mp3
- [ ] C:\SoundBoard\Don\WRAPUP\YearBuilt.mp3
- [ ] C:\SoundBoard\Don\WRAPUP\and that okay with you correct.mp3
- [ ] C:\SoundBoard\Don\WRAPUP\bad connection.mp3
- [ ] C:\SoundBoard\Don\intro\wrong number Don.mp3
- [x] C:\Soundboard\Don\DRIVER INFO\dob1.mp3
- [ ] C:\Soundboard\Don\INTRO\DonCALLING.mp3
- [x] C:\Soundboard\Don\INTRO\INTRO3.mp3
- [x] C:\Soundboard\Don\REACTIONS\OK.mp3
- [x] C:\Soundboard\Don\REACTIONS\OK2.mp3
- [x] C:\Soundboard\Don\REACTIONS\okGreat.mp3
- [ ] C:\Soundboard\Don\VEHICLE INFO\What is the model of the Car 1.mp3
- [ ] C:\Soundboard\Don\VEHICLE INFO\Who Makes That Vehicle.mp3

Not as important but we'll want these later:
- [ ] C:\SoundBoard\Don\NAMES
- [ ] C:\Soundboard\Don\Birthday\" + dobby[2] + ".mp3
- [ ] C:\Soundboard\Don\Birthday\" + moday + ".mp3
- [ ] C:\soundboard\Don\REBUTTALS\CAN YOU JUST VERIFY THE DAY.mp3
- [ ] C:\soundboard\Don\REBUTTALS\CAN YOU JUST VERIFY THE MONTH.mp3
- [ ] C:\soundboard\Don\REBUTTALS\CAN YOU JUST VERIFY THE YEAR.mp3

#### Additional info:
 - **Bot Revision**: https://github.com/LCN-Dev/GoogleBot/commit/fd4b9c10245a096d5188d9d524b8f432d15517ca
 - **Anything else you may wish to add**: 
![donbot](https://cloud.githubusercontent.com/assets/6484985/24221201/c25ac4f8-0f23-11e7-9eab-e06e61e4f0ff.gif)

**Comment by NicksAccount** [comment]
What's wrong with the spouse DOB and name files?

**Comment by SpadesNeil** [comment]
"Have either of you served in the military?" We already ask if the first person has served in the military and don't ask the second question unless we know they have a spouse.

The correct one would be, "Has your spouse served in the military?"

**Comment by NicksAccount** [comment]
I can get a new one. but what's wrong with DOB and name????

**Comment by SpadesNeil** [comment]
We don't have audio for names, because that would take forever to do. Or are you talking about something else?

There's nothing wrong with the DOB question. I even checkmarked dob1.mp3 off as done.

**Comment by NicksAccount** [comment]
Spouse DOB and spouse name

**Comment by SpadesNeil** [comment]
I must have missed those files if we have them already.
