### ISSUE TITLE
"No Speech" alert in Slack

### ISSUE THREAD

**Issue by SpadesNeil** [LCN-Dev/GoogleBot#161]
#### Brief description of the issue:
If the bot consistently goes through, say, 10 calls in a row without _any_ speech what so ever, there's a chance that something was configured wrongly. If the bot could alert Slack, we could have better situational awareness and know to investigate the bot to see if everything is okay or it's just having bad luck.

#### Additional info:
 - **Bot Revision**: https://github.com/LCN-Dev/GoogleBot/commit/fd4b9c10245a096d5188d9d524b8f432d15517ca

**Comment by MTS11648** [comment]
I can do this.
