### ISSUE TITLE
The Don Bot Audio

### ISSUE THREAD

**Issue by NicksAccount** [LCN-Dev/GoogleBot#163]
The following files must be recorded before The Don Bot can be fully functional.

We have some of these already, they just need to be sorted. Some of them we do have aren't good for the bot for whatever reason.

- [ ] C:/SoundBoard/Don/Birthday/0105.mp3
- [ ] C:/SoundBoard/Don/Birthday/0111.mp3
- [ ] C:/SoundBoard/Don/Birthday/0112.mp3
- [ ] C:/SoundBoard/Don/Birthday/0119.mp3
- [ ] C:/SoundBoard/Don/Birthday/0202.mp3
- [ ] C:/SoundBoard/Don/Birthday/0212.mp3
- [ ] C:/SoundBoard/Don/Birthday/0214.mp3
- [ ] C:/SoundBoard/Don/Birthday/0328.mp3
- [ ] C:/SoundBoard/Don/Birthday/0411.mp3
- [ ] C:/SoundBoard/Don/Birthday/0516.mp3
- [ ] C:/SoundBoard/Don/Birthday/0522.mp3
- [ ] C:/SoundBoard/Don/Birthday/0523.mp3
- [ ] C:/SoundBoard/Don/Birthday/0531.mp3
- [ ] C:/SoundBoard/Don/Birthday/0622.mp3
- [ ] C:/SoundBoard/Don/Birthday/0709.mp3
- [ ] C:/SoundBoard/Don/Birthday/0710.mp3
- [ ] C:/SoundBoard/Don/Birthday/0713.mp3
- [ ] C:/SoundBoard/Don/Birthday/0724.mp3
- [ ] C:/SoundBoard/Don/Birthday/0725.mp3
- [ ] C:/SoundBoard/Don/Birthday/0727.mp3
- [ ] C:/SoundBoard/Don/Birthday/0820.mp3
- [ ] C:/SoundBoard/Don/Birthday/0827.mp3
- [ ] C:/SoundBoard/Don/Birthday/0902.mp3
- [ ] C:/SoundBoard/Don/Birthday/0913.mp3
- [ ] C:/SoundBoard/Don/Birthday/0918.mp3
- [ ] C:/SoundBoard/Don/Birthday/1002.mp3
- [ ] C:/SoundBoard/Don/Birthday/1009.mp3
- [ ] C:/SoundBoard/Don/Birthday/1015.mp3
- [ ] C:/SoundBoard/Don/Birthday/1020.mp3
- [ ] C:/SoundBoard/Don/Birthday/1030.mp3
- [ ] C:/SoundBoard/Don/Birthday/1103.mp3
- [ ] C:/SoundBoard/Don/Birthday/1109.mp3
- [ ] C:/SoundBoard/Don/Birthday/1117.mp3
- [ ] C:/SoundBoard/Don/Birthday/1120.mp3
- [ ] C:/SoundBoard/Don/Birthday/1122.mp3
- [ ] C:/SoundBoard/Don/Birthday/1124.mp3
- [ ] C:/SoundBoard/Don/Birthday/1127.mp3
- [ ] C:/SoundBoard/Don/Birthday/1201.mp3
- [ ] C:/SoundBoard/Don/Birthday/1207.mp3
- [ ] C:/SoundBoard/Don/Birthday/1215.mp3
- [ ] C:/SoundBoard/Don/Birthday/1222.mp3
- [ ] C:/SoundBoard/Don/Birthday/1916.mp3
- [ ] C:/SoundBoard/Don/Birthday/1917.mp3
- [ ] C:/SoundBoard/Don/Birthday/1918.mp3
- [ ] C:/SoundBoard/Don/Birthday/1919.mp3
- [ ] C:/SoundBoard/Don/Birthday/1920.mp3
- [ ] C:/SoundBoard/Don/Birthday/1921.mp3
- [ ] C:/SoundBoard/Don/Birthday/1922.mp3
- [ ] C:/SoundBoard/Don/Birthday/1923.mp3
- [ ] C:/SoundBoard/Don/Birthday/1924.mp3
- [ ] C:/SoundBoard/Don/Birthday/1925.mp3
- [ ] C:/SoundBoard/Don/Birthday/1927.mp3
- [ ] C:/SoundBoard/Don/Birthday/1928.mp3
- [ ] C:/SoundBoard/Don/Birthday/1929.mp3
- [ ] C:/SoundBoard/Don/Birthday/1931.mp3
- [ ] C:/SoundBoard/Don/Birthday/1932.mp3
- [ ] C:/SoundBoard/Don/Birthday/1936.mp3
- [ ] C:/SoundBoard/Don/Birthday/1938.mp3
- [ ] C:/SoundBoard/Don/Birthday/1940.mp3
- [ ] C:/SoundBoard/Don/Birthday/1941.mp3
- [ ] C:/SoundBoard/Don/Birthday/1943.mp3
- [ ] C:/SoundBoard/Don/Birthday/1945.mp3
- [ ] C:/SoundBoard/Don/Birthday/1948.mp3
- [ ] C:/SoundBoard/Don/Birthday/1949.mp3
- [ ] C:/SoundBoard/Don/Birthday/1966.mp3
- [ ] C:/SoundBoard/Don/Birthday/1968.mp3
- [ ] C:/SoundBoard/Don/Birthday/1972.mp3
- [ ] C:/SoundBoard/Don/Birthday/1973.mp3
- [ ] C:/SoundBoard/Don/Birthday/1974.mp3
- [ ] C:/SoundBoard/Don/Birthday/1975.mp3
- [ ] C:/SoundBoard/Don/Birthday/1977.mp3
- [ ] C:/SoundBoard/Don/Birthday/1978.mp3
- [ ] C:/SoundBoard/Don/Birthday/1979.mp3
- [ ] C:/SoundBoard/Don/Birthday/1989.mp3
- [ ] C:/SoundBoard/Don/Birthday/1990.mp3
- [ ] C:/SoundBoard/Don/Birthday/1997.mp3
- [ ] C:/SoundBoard/Don/Birthday/1998.mp3
- [ ] C:/SoundBoard/Don/DRIVER INFO/spouse military.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Domains/and your email is still.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Domains/aol.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Domains/att.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Domains/comcast.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Domains/gmail.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Domains/hotmail.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Domains/live.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Domains/msn.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Domains/outlook.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Domains/sbcglobal.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Domains/usa.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Domains/verizon.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Domains/yahoo.mp3
- [ ] C:/SoundBoard/Don/EMAIL/EMAIL.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/-1.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/-2.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/-3.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/.1.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/.2.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/.3.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/01.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/02.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/03.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/11.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/12.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/13.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/21.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/22.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/23.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/31.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/32.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/33.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/41.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/42.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/43.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/51.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/52.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/53.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/61.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/62.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/63.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/71.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/72.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/73.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/81.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/82.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/83.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/91.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/92.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/93.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/A1.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/A2.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/A3.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/B1.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/B2.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/B3.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/C1.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/C2.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/C3.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/D1.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/D2.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/D3.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/E1.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/E2.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/E3.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/F1.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/F2.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/F3.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/G1.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/G2.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/G3.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/H1.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/H2.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/H3.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/I1.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/I2.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/I3.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/J1.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/J2.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/J3.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/K1.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/K2.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/K3.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/L1.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/L2.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/L3.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/M1.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/M2.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/M3.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/N1.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/N2.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/N3.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/O1.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/O2.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/O3.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/P1.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/P2.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/P3.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/Q1.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/Q2.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/Q3.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/R1.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/R2.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/R3.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/S1.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/S2.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/S3.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/T1.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/T2.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/T3.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/U1.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/U2.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/U3.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/V1.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/V2.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/V3.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/W1.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/W2.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/W3.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/X1.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/X2.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/X3.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/Y1.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/Y2.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/Y3.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/Z1.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/Z2.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/Z3.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/_1.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/_2.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Letters/_3.mp3
- [ ] C:/SoundBoard/Don/EMAIL/and your email.mp3
- [ ] C:/SoundBoard/Don/INSURANCE INFO/Ins provider 3.mp3
- [ ] C:/SoundBoard/Don/INSURANCE INFO/Years with 2.mp3
- [ ] C:/SoundBoard/Don/INSURANCE INFO/Years with 3.mp3
- [ ] C:/SoundBoard/Don/INTRO/INTROREPEAT.mp3
- [ ] C:/SoundBoard/Don/REBUTTALS/nothing to be interested in.mp3
- [ ] C:/SoundBoard/Don/WRAPUP/TCPAREBUT.mp3
- [ ] C:/SoundBoard/Don/EMAIL/EMAIL.mp3
- [ ] C:/SoundBoard/Don/REACTIONS/Is that correct.mp3

#### Additional info:
 - **Bot Revision**: https://github.com/LCN-Dev/GoogleBot/commit/fd4b9c10245a096d5188d9d524b8f432d15517ca
 - **Anything else you may wish to add**: 
![donbot](https://cloud.githubusercontent.com/assets/6484985/24221201/c25ac4f8-0f23-11e7-9eab-e06e61e4f0ff.gif)

**Comment by SpadesNeil** [comment]
Replaces #159

**Comment by SpadesNeil** [comment]
We do still need a few files, but then we can start testing:

- C:\SoundBoard\Don\INTRO\HELLO.mp3 is needed during call start, and if Cheryl is trying to get contact back.
- C:\SoundBoard\Don\WRAPUP\and that okay with you correct.mp3 is needed during TCPA2.
- C:\SoundBoard\Don\PERSONAL INFO\Last Name.mp3 is needed because we require a last name.

Anything we don't need ever, I deleted from the list above. Whatever remains that I didn't mention in this comment are just things we will require to get the bot _fully_ functional.

**Comment by SpadesNeil** [comment]
Downing priority to "Severe" because we can now run a prototype once we have those audio files.

Note that the file checking function WILL NOT check for Don's audio files yet.

**Comment by NicksAccount** [comment]
Awesome. I have those 3 files now!

**Comment by NicksAccount** [comment]
I've got some extra rebuttals. I'm currently trying to eliminate the ones on the list, but on the way of that, i'm also finding extra ones. For example, a rebuttal for: "Why do you need my birthday?" and "Why do you need to know that?"

**Comment by SpadesNeil** [comment]
Yes, I noticed a number of duplicates appearing on the list, as well as unused rebuttals. Just use your judgement on them, and if you're unsure of where in the code they show up, you can use Visual Studio to search for the files. I already eliminated a number of them from the list that were useless, but there's probably more.

If you find an audio file that never appears in Agent.cs though, it's a useless file as far as calls are concerned.

**Comment by SpadesNeil** [comment]
Need a couple more files if you get the chance.

- INTRO3.mp3 needs to be redone to _not_ ask about insurance providers or where they live. We're instead just going to ask during the actual question like it should have been all along, because that's more sensible and consistent.
- DRIVER INFO/Are you still living in.mp3 is needed so we actually ask a question before saying the state.

The Don Bot (#160) is otherwise ready for more testing.

**Comment by SpadesNeil** [comment]
Apparently I forgot to lower the priority.

**Comment by NicksAccount** [comment]
The clip for the intro ends on "quote" and the state clips go as "Are you still in __________"

**Comment by SpadesNeil** [comment]
So we have all states but Wyoming and Delaware. We're not recording Hawaii or Alaska because we don't cover those.

**Comment by SpadesNeil** [comment]
1271 is now running the DonBot! :D

**Comment by NicksAccount** [comment]
We don't call MA or NH. Also, I can get those files today (if i can find them haha), And i'll clip that Florida audio

**Comment by NicksAccount** [comment]
Also, i'm gonna grab a rebuttal for "Which one?" to the vehicle question if i can find it and also a "How many vehicles do you have?" so he doesnt ask "What kind of car do you drive?" then ask for the year make and model.

**Comment by SpadesNeil** [comment]
Oh okay then. I'll just add MA and NH to the list of exceptions.

**Comment by SpadesNeil** [comment]
Heads up that Louisiana was misspelled as Louisianna. I fixed it in my files.

**Comment by SpadesNeil** [comment]
C:\SoundBoard\Don\DRIVER INFO\Marital Status.mp3 is marked as done, but the file is not found?

**Comment by SpadesNeil** [comment]
I don't really understand the current address rebuttal. If I recall correctly, that is supposed to be something along the lines of explaining why we need an address because where they park their car influences rates.

**Comment by SpadesNeil** [comment]
Local agents and carriers in your area.mp3 doesn't quite work in the context it's currently used. I'd suggest just removing the long "Noooo" at the start and it'd be good.

```else if (resp.Contains("how many calls will i get") || resp.Contains("how many calls am i going to get") || resp.Contains("how many calls am i gonna get") || response.Contains("will i get a bunch of calls") || response.Contains("how many people will call me") || response.Contains("how many people are going to call me") || response.Contains("i don't want a bunch of call") || response.Contains("will i get a million calls") || response.Contains("i don't want a lot of calls")) // DON BOT TEMP
                {
                    clip = @"C:\SoundBoard\Don\REBUTTALS\Local agents and carriers in your area.mp3";
                    Conversation.RollTheClip(clip);
                    currentlyRebuttaling = true;
                    return true;
                }```

**Comment by SpadesNeil** [comment]
I've updated the above list for all currently missing audio.

**Comment by NicksAccount** [comment]
Renaming the names correctly today. 

Ex;
Nick 1.mp3

should i also copy 2 of each to make;
Nick 2.mp3
Nick 3.mp3
?

**Comment by SpadesNeil** [comment]
Actually, I found a way around this issue. We don't need the two copies of the name.

**Comment by SpadesNeil** [comment]
All the names are fixed and included in a new upload of the Don Bot soundboard which I'll post before tonight is up.

**Comment by SpadesNeil** [comment]
Updated missing files.

**Comment by SpadesNeil** [comment]
@NicksAccount We're still missing a lot of audio.

**Comment by NicksAccount** [comment]
Do you have examples? We don't have letters and numbers. What else?

**Comment by SpadesNeil** [comment]
Everything unchecked on the checkbox is not currently in the DonBot. This list was compiled using the MISSING_FILES_LOG.log file that is generated at runtime when files are missing. Letters and numbers aren't the only thing here.

**Comment by NicksAccount** [comment]
We have the files on that checklist besides the letters and numbers, they're just not named exactly that. For example, "Got it", there's "very good", "OK Great",  "alright" (3 different files). And for things like "Great, what's your best guess" we have "best guess" and "Where did you get my info" also has a rebuttal and it's used on the manual soundboard already for the "Where'd you get my info" button.

**Comment by SpadesNeil** [comment]
For some reason Ryan and I don't have those files on our computers. Can you compile what's missing into a zip for us?

Preferably pathed correctly, too.

**Comment by SpadesNeil** [comment]
Updated the list. Still missing years, but I do have the raw file for those.

I also deleted a number of really old and terrible birthday clips from the first round of cut-out audio for the Don Bot. If you see audio clips and you're thinking, "I swear I got those," then yes, you do, but you probably have the really bad versions of them.

**Comment by SpadesNeil** [comment]
I'm not checking off that list. Everything we need is done. This is resolved.
