### ISSUE TITLE
Server Bots [Mostly] Dysfunctional

### ISSUE THREAD

**Issue by MTS11648** [LCN-Dev/GoogleBot#164]
#### Brief description of the issue:
The server bots don't get any speech and hang-up.
#### What happened?:
The bots don't connect to the proper socket to get speech.
#### What _should_ have happened?:
The bots should work and get speech.
#### Steps to reproduce:
1) Run a server bot.
2) Watch it not work.

**Comment by NicksAccount** [comment]
This problem should be all set. From what it looks like, bots are back up n' running.

**Comment by SpadesNeil** [comment]
"Solved" isn't the word I'd use but it's certainly reduced. I want to find out if there were any recent wiring changes at the office, or if there's anything else we can do to help the server not run like trash.

**Comment by NicksAccount** [comment]
The intro is a little tough w/ connecting but once it gets connected, the call takes off. Around 7 bots up and connection gets shaky.

**Comment by NicksAccount** [comment]
We did get a lead on the server, however. Just being tough.

**Comment by SpadesNeil** [comment]
If you get the chance, can you ask Dave about any recent wiring changes at the office? Anything from just before we started having these issues.

I don't know if it will help any, but it's worth asking I suppose.

**Comment by NicksAccount** [comment]
Nothing other than them disconnecting the internet to do some work, but that happened a day or two after this problem occurred.

**Comment by NicksAccount** [comment]
"Error Connecting. Timed Out" 
is what has been coming up a lot

**Comment by NicksAccount** [comment]
I turned off office noise on the server bots and it's not a complete change, but the speech is connecting more frequently. I'm not sure how this would affect it, but it seems to have somewhat of a difference. Nothing major, though.

**Comment by MTS11648** [comment]
I don't know exactly what Justin came by and did, but I still can't help but feel this is more of a "server being in the new office" problem rather than a "we messed up everything in the programming" problem.

**Comment by SpadesNeil** [comment]
It's actually a bit of both. Well, not that we messed up, but that our stuff inevitably becomes outdated and we have to fix that. It was the culmination of several problems, including the shitty unreliable server connection.

**Comment by SpadesNeil** [comment]
Okay so no wiring changes. We're actually doing better with no server bots than we ever have with server bots, so I am convinced the server is just flat out terrible.

We had 32 leads on just 21 bots today.

**Comment by SpadesNeil** [comment]
Closing this for now.
