### ISSUE TITLE
Reformat the vehicle question

### ISSUE THREAD

**Issue by SpadesNeil** [LCN-Dev/GoogleBot#165]
#### Brief description of the issue:
Currently, we just ask the YMM in one quick question. What if we split it up into 3 questions?

1. "What's the make of the car you drive? Ford, Subaru, Toyota?"
2. "And what is the model?"
3. "And do you know what year it was built?"

This could help accuracy of leads.

#### Additional info:
 - **Bot Revision**: https://github.com/LCN-Dev/GoogleBot/pull/160/commits/96b4bbea0d0cbc0b2cc0c0c36bdbab1935784535 (DonBot)

**Comment by MTS11648** [comment]
I like it but the vehicle isn't really the most important question on the form. For example, if we just get "2008 Honda" we can still technically submit the lead with that information. I could see this same concept being more useful when applied to something like the address question (What is your address, what city is that in, etc.). Just sounds like a lot of extra work for the auditors if you ask me and you know as well as I do that that is the last thing we want.

**Comment by SpadesNeil** [comment]
I just realized this is technically a duplicate of https://github.com/LCN-Dev/GoogleBot/issues/140
