### ISSUE TITLE
"Oh they're a great company" occasionally skips like a broken discman

### ISSUE THREAD

**Issue by SpadesNeil** [LCN-Dev/GoogleBot#168]
#### Brief description of the issue:
And I have no idea why but it's annoying.

#### Steps to reproduce:
Unknown

#### Additional info:
 - **Bot Revision**: https://github.com/LCN-Dev/GoogleBot/commit/90c525818dbdf6f8e73020ffc59f580653b5b3cb
 - **Anything else you may wish to add**: Just remove it for now I say.

**Comment by SpadesNeil** [comment]
shut up I'm sleepy

**Comment by MTS11648** [comment]
What.

**Comment by SpadesNeil** [comment]
Point is, it's dodgy and bad.
