### ISSUE TITLE
When email is asked, if "at (domain)" is not heard, Cheryl won't move on

### ISSUE THREAD

**Issue by NicksAccount** [LCN-Dev/GoogleBot#180]
Leo had an idea so I figure why not throw it here.
#### What happened?:
Cheryl hears "Nah i don't wanna give that out" (or something like that) and doesn't rebuttal for the email and continues on to the next question
#### What _should_ have happened?:
When Cheryl asks for the email, if "at yahoo (google, hotmail, comcast, etc.)" is not heard, Cheryl will say her email rebuttal (i'll try to grab a better one of those).
This can help out with people not giving emails.  
#### Steps to reproduce:
- listen to a call
- hear someone say something other than an email to the email question
- listen to Cheryl not care and move on. Bad robot!
#### Additional info:
 - **Bot Revision**: Found under the hidden folder /.git/packed-refs, which you open with notepad and copy the second line of text to paste here.
 - **Anything else you may wish to add**: (Related issues, console output, error notices, screenshots, etc.)

**Comment by NicksAccount** [comment]
whoops, i deleted the brief description section.

**Comment by SpadesNeil** [comment]
Unfortunately we tried exactly this.

https://github.com/LCN-Dev/GoogleBot/pull/91

It made things worse.

**Comment by SpadesNeil** [comment]
However I just did a thing that might make this work.
