### ISSUE TITLE
Address question getting skipped

### ISSUE THREAD

**Issue by NicksAccount** [LCN-Dev/GoogleBot#195]
#### Brief description of the issue:
On some calls when someone answers the address question, even if they don't say an address (which I can see would be hard to catch cause of how many ways an address can go), Cheryl will go onto say "I just need an email" and most people will say, "Oh! My EMAIL address!"
#### What happened?:
^

#### What _should_ have happened?:
Cheryl gets something for an address, (maybe picks up a # which can signal they're saying an address)
#### Steps to reproduce:
Listen to some calls

**Comment by SpadesNeil** [comment]
We may be able to have the address question play out similarly to the email, but I need _all_ the possible ways a street can be named in the United States.

So far my ideas are...

Street, Boulevard, Way, Road, Circle, Lane, North, South, East, West, Highway, Avenue.

If we check that the address is invalid, as in, doesn't contain any of this information, we can play askForRepeat(), and if they go, "What was that?" or "What was the question?" that already triggers customerMisunderstands().

This list of names is not complete so I need to research this. It's absolutely possible.

**Comment by SpadesNeil** [comment]
https://en.wikipedia.org/wiki/Street_or_road_name#Street_type_designations Jackpot.

**Comment by NicksAccount** [comment]
this has them all:

http://pe.usps.gov/text/pub28/28apc_002.htm

**Comment by SpadesNeil** [comment]
That's even better. I got it from here.
