### ISSUE TITLE
After intro (sometimes on TCPA) customer asks something along the lines of "Is this for my auto insurance?"

### ISSUE THREAD

**Issue by NicksAccount** [LCN-Dev/GoogleBot#201]
#### Brief description of the issue:
Listening to some calls, we lose lots of people on things like after the intro and the tcpa the person saying, "This is for my auto insurance?" "Auto insurance?" "For my car?" "Who is my AUTO provider?" etc. If we could code a "Yes, that is correct" or even just "Yes", I feel like it'll up leads a bit
#### What happened?:
Customer asks, "My auto insurance company?" and Cheryl says "When is your policy due to expire?"
#### What _should_ have happened?:
She answers the person with a yes
#### Steps to reproduce:
Ask "for my auto insurance?" after intro / tcpa
#### Additional info:
 - **Bot Revision**: Found under the hidden folder /.git/packed-refs, which you open with notepad and copy the second line of text to paste here.
 - **Anything else you may wish to add**: (Related issues, console output, error notices, screenshots, etc.)

**Comment by SpadesNeil** [comment]
How about THISISTOGIVENEWQUOTE.mp3? That work too?

**Comment by NicksAccount** [comment]
That would work! Good call. 

Also, just so i dont have to make another issue, is "again" a catch to repeat something? Heard a few times on the intro and tcpa people say "Can you say that again?" Could've been picked up wrong cause i'd imagine it's in there

**Comment by SpadesNeil** [comment]
I'll just fix it while I'm here. Normally you'd have to make new issues but it seems rather silly to do when I'm working on these problems _right now_.

**Comment by NicksAccount** [comment]
Right on, gotchya!

**Comment by SpadesNeil** [comment]
```response.Contains("say that again")``` added to #200 

Gonna fix the other problems here under that PR too. You'll see the results shortly.
