### ISSUE TITLE
Cheryl not taking "No" for an answer

### ISSUE THREAD

**Issue by NicksAccount** [LCN-Dev/GoogleBot#204]
#### Brief description of the issue:
Listening to 1277 (Big Kev 4/19 16:18 version), and Cheryl gets to the TCPA and the guy says "No" about 6 or 7 times, and the bot picked up "No", however, Cheryl kept saying her famous line "...and that's okay with you, correct?"
#### What happened?:
Cheryl hears and picks up "No" on TCPA and never surrenders her question
#### What _should_ have happened?:
Cheryl hangup the call after a nice "Have a good day" or something
#### Steps to reproduce:
Get to TCPA
Say "NO!"
"...and that's okay with you, correct?"
#### Additional info:
 - **Bot Revision**: Found under the hidden folder /.git/packed-refs, which you open with notepad and copy the second line of text to paste here.
 - **Anything else you may wish to add**: (Related issues, console output, error notices, screenshots, etc.)

**Comment by SpadesNeil** [comment]
May have something to do with #196

**Comment by MTS11648** [comment]
This has been resolved in #211.
