### ISSUE TITLE
Preload all the files in the /NAMES directory so the bot can search from memory instead of off the disk.

### ISSUE THREAD

**Issue by SpadesNeil** [LCN-Dev/GoogleBot#208]
#### Brief description of the issue:
When the bot runs at the start of a call, it is programmed to find the name of the customer off a list. This is slow and inefficient, and if that name doesn't exist at all, it takes the maximum amount of time to locate it only to realize there's nothing possible to find, so it defaults to the "Hello?" greeting.

This is terrible and inefficient. What I propose is to preload a list of good file paths at the startup of the program for the names. The names will be kept in memory for easy access, so that when the bot needs to search names, it can do so much faster than what is possible reading from disk.

#### Additional info:
 - **Bot Revision**: https://github.com/LCN-Dev/GoogleBot/commit/f9c69cdaef0171713b67ca4e51354579ce0d56ab

**Comment by MTS11648** [comment]
as if the file check doesn't already delay the bot loading enough ;)
