### ISSUE TITLE
Spell the customer's email

### ISSUE THREAD

**Issue by SpadesNeil** [LCN-Dev/GoogleBot#213]
#### Brief description of the issue:
Cheryl should attempt to spell the customer's email if it's available, similar to the birthday question.

#### What _should_ have happened?:
- If field isn't empty, spell the email.
- Else, say "Can you also verify your email?" (We don't have a clip like this yet, but we should.)

#### Additional info:
 - **Bot Revision**: https://github.com/LCN-Dev/GoogleBot/commit/a72392cc82491862fdea606b0e08dc990c4cfacf
 - **Anything else you may wish to add**: Gonna need @NicksAccount's help for this.

Note to self: There's some derelict code located at line 2025 in Agent.cs, under ```public static async Task<bool> SpellString(string data)```

**Comment by SpadesNeil** [comment]
A few things we need to change before this is done: 
- The email domain quality isn't ideal.
- "At" "Dot" "Underscore" and "Dash" do not have audio files.
- Domain suffixes need to have their own audio files. "Dot com" "Dot org" "Dot net" "Dot gov" "Dot edu" and so on.

**Comment by NicksAccount** [comment]
I gave Kathleen a paper with those for Cheryl to record, awaiting results and recordings.

**Comment by NicksAccount** [comment]
an update on the files:

![tenor](https://cloud.githubusercontent.com/assets/26008768/25450377/b8cf4d76-2a8c-11e7-9fef-d77cf405a97c.gif)

**Comment by NicksAccount** [comment]
Doing the test and oddly enough delta didn't work but i was still able to get to the email question obviously. Sounds alright, sounds pretty robotic but it's cool that it actually works. I can change around the "dot" and "dash" clips to sound more fluent with the letters. Also, I noticed (yeah it's just a test version,) that if Cheryl doesn't hear anything the first time she says a question, even if something is heard before the first "hello??" she still goes into her spiel about bad connection and hangs up.

**Comment by NicksAccount** [comment]
Sounds a bit off too with the letters if it's a repeated letter. Would there be a way to determine to use a middle end and beginning instead of using the same letter file twice?

**Comment by SpadesNeil** [comment]
We can easily do adjustments like that, yes. I also wonder if it's possible to make small adjustments to pitch with the program its self, doing so at random.

**Comment by michael1253** [comment]
https://github.com/LCN-Dev/GoogleBot/issues/249 we got a small problem
