### ISSUE TITLE
You can only rebut the TCPA 1 time

### ISSUE THREAD

**Issue by NicksAccount** [LCN-Dev/GoogleBot#216]
#### Brief description of the issue:
While listening to a call, I heard cheryl rebut someone's "Nah, im all set" on the tcpa. Then, the guy says, "No, im ok." to which cheryl rebuts. Aaaand again he says no, so cheryl goes to the classic "and thats okay with you?" to which we got a "yeah." 
Now, what I didn't know (and found out after this call) is that you're only allowed to rebut the TCPA 1 time and 1 time only. 
#### What happened?:
Cheryl rebutted 3 times. It worked (and sounded very good), but it's not allowed. 
#### What _should_ have happened?:
She should've taken the L on that one. 
#### Steps to reproduce:
Listen to a call
Get to TCPA
Hear a rebuttal

#### Additional info:
 - **Bot Revision**: Found under the hidden folder /.git/packed-refs, which you open with notepad and copy the second line of text to paste here.
 - **Anything else you may wish to add**: (Related issues, console output, error notices, screenshots, etc.)

**Comment by SpadesNeil** [comment]
All that work for nothing...

**Comment by NicksAccount** [comment]
Not our faults, we didn't know. And honestly what you programmed was successful in getting the lead, just a shame we can't use it. 

THE BOTS WILL KEEP ON KEEPIN' ON BABY

http://orig07.deviantart.net/5982/f/2011/268/8/b/robots_unite_by_mjrainwater-d4ay83j.png

**Comment by SpadesNeil** [comment]
Credit to @MTS11648 for that one. He programmed most of it. I just found the flaws and fixed them to make it work correctly.
