### ISSUE TITLE
hotmail.mp3 is the wrong .mp3

### ISSUE THREAD

**Issue by SpadesNeil** [LCN-Dev/GoogleBot#232]
#### Brief description of the issue:
**NICK I FUCKED UP.**

#### What happened?:
**I PUT THE WRONG HOTMAIL.mp3 FILE ON THE BOTS AND NOW CHERYL GOES COMPLETELY FUBAR.**

#### What _should_ have happened?:
**ANYTHING BUT THIS**

#### Steps to reproduce:
- Put sleepy Jer in charge of updating the bots on Saturday morning.
- Be a caller with a Hotmail email address.
- BE SUPER CONFUSED.
- AAAAHHHHHH

#### Additional info:
 - **Bot Revision**: N/A

**Comment by NicksAccount** [comment]
Got it. Doing that!

**Comment by SpadesNeil** [comment]
Thanks. Did you get them all?

**Comment by SpadesNeil** [comment]
Mark this as "Resolved" and close it once you're sure it's resolved.
