### ISSUE TITLE
Rebuild the Don Bot intro

### ISSUE THREAD

**Issue by SpadesNeil** [LCN-Dev/GoogleBot#237]
#### Brief description of the issue:
The DonBot's old branch is so outdated and FUBAR that it's not worth trying to work with it. As a consequence, I'm restarting work on the Don Bot from scratch.

Here's things I need to do:
- [x] Have Don Bot read the state again during the intro.
- [x] Have Don Bot read the city _and_ state if it's a known location.
- [x] Cry myself to sleep.

#### Additional info:
 - **Bot Revision**: 7eb9e0af3c61fcd76c8cc0e4380725e0fd22ea78

**Comment by SpadesNeil** [comment]
- [x] C:/SoundBoard/Don/DRIVER INFO/Spouses Date of Birth.mp3
- [x] C:/SoundBoard/Don/DRIVER INFO/Spouses First name.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Domains/and your email is still.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Domains/aol.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Domains/att.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Domains/comcast.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Domains/gmail.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Domains/hotmail.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Domains/live.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Domains/msn.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Domains/outlook.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Domains/sbcglobal.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Domains/usa.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Domains/verizon.mp3
- [ ] C:/SoundBoard/Don/EMAIL/Domains/yahoo.mp3
- [ ] C:/SoundBoard/Don/EMAIL/EMAIL.mp3
- [ ] C:/SoundBoard/Don/EMAIL/and your email.mp3
- [ ] C:/SoundBoard/Don/INSURANCE INFO/Ins provider 3.mp3
- [ ] C:/SoundBoard/Don/INSURANCE INFO/Years with 2.mp3
- [ ] C:/SoundBoard/Don/INSURANCE INFO/Years with 3.mp3
- [ ] C:/SoundBoard/Don/INTRO/INTROREPEAT.mp3
- [ ] C:/SoundBoard/Don/INTRO/THISISTOGIVENEWQUOTE.mp3
- [ ] C:/SoundBoard/Don/INTRO/wrong number cheryl.mp3
- [ ] C:/SoundBoard/Don/REACTIONS/Got it 3.mp3
- [ ] C:/SoundBoard/Don/REACTIONS/OTAGC.mp3
- [ ] C:/SoundBoard/Don/REACTIONS/can you repeat that 3.mp3
- [ ] C:/SoundBoard/Don/REACTIONS/can you repeat that 4.mp3
- [ ] C:/SoundBoard/Don/REACTIONS/no not at all 1.mp3
- [ ] C:/SoundBoard/Don/REACTIONS/yeah 1.mp3
- [ ] C:/SoundBoard/Don/REBUTTALS/Can You Just Verify the month.mp3
- [ ] C:/SoundBoard/Don/REBUTTALS/Email Rebuttal 2.mp3
- [ ] C:/SoundBoard/Don/REBUTTALS/Email Rebuttal.mp3
- [ ] C:/SoundBoard/Don/REBUTTALS/I'm required to have you verify it first.mp3
- [ ] C:/SoundBoard/Don/REBUTTALS/IllBeAbout20Seconds.mp3
- [ ] C:/SoundBoard/Don/REBUTTALS/Is This the Spouse.mp3
- [ ] C:/SoundBoard/Don/REBUTTALS/Let me Just confirm a few things.mp3
- [ ] C:/SoundBoard/Don/REBUTTALS/My spouse takes care of that.mp3
- [ ] C:/SoundBoard/Don/REBUTTALS/NotThatCheap.mp3
- [ ] C:/SoundBoard/Don/REBUTTALS/P.O Box rebuttal.mp3
- [ ] C:/SoundBoard/Don/REBUTTALS/Sorry to Hear That 2.mp3
- [ ] C:/SoundBoard/Don/REBUTTALS/This info.mp3
- [ ] C:/SoundBoard/Don/REBUTTALS/ThisIsJustAQuickProccess.mp3
- [ ] C:/SoundBoard/Don/REBUTTALS/What was your name 3.mp3
- [ ] C:/SoundBoard/Don/REBUTTALS/nothing to be interested in.mp3
- [ ] C:/SoundBoard/Don/REBUTTALS/scam rebuttal.mp3
- [ ] C:/SoundBoard/Don/REBUTTALS/sorry.mp3
- [ ] C:/SoundBoard/Don/REBUTTALS/this info.mp3
- [ ] C:/SoundBoard/Don/REBUTTALS/where did you get my info.mp3
- [ ] C:/SoundBoard/Don/REBUTTALS/which address rebuttal.mp3
- [ ] C:/SoundBoard/Don/TIE INS/Great What's Your Best Guess.mp3
- [ ] C:/SoundBoard/Don/VEHICLE INFO/2nd Vehicle.mp3
- [ ] C:/SoundBoard/Don/VEHICLE INFO/Fourth Vehicle.mp3
- [ ] C:/SoundBoard/Don/VEHICLE INFO/Third Vehicle.mp3
- [ ] C:/SoundBoard/Don/WRAPUP/TCPAREBUT.mp3
- [ ] C:/SoundBoard/Don/WRAPUP/TCPA_REBUTTAL_3.mp3
- [ ] C:/SoundBoard/Don/WRAPUP/bad connection.mp3
- [ ] C:/SoundBoard/Don/EMAIL/EMAIL.mp3
- [ ] C:/SoundBoard/Don/REACTIONS/Is that correct.mp3

**Comment by SpadesNeil** [comment]
- [x] Cry myself to sleep.

**Comment by NicksAccount** [comment]
That zip i sent last night contained some of these, like an answer to "can they email", a clip where he says it will be very quick, a "where did you get my info" rebuttal, an address question and something for "THISISTOGIVEANEWQUOTE"

**Comment by SpadesNeil** [comment]
Might need a new "wrong number.mp3" file, since it sounded a bit awkward, but otherwise these are good.
