### ISSUE TITLE
DonBot will ask customer to repeat if they answer "No" to the veteran question

### ISSUE THREAD

**Issue by NicksAccount** [LCN-Dev/GoogleBot#248]
#### Brief description of the issue:
when donbot asks a person about military service, if the person answers with a "No" he asks them to repeat
#### What happened?:
donbot asks military question; repeats if the customer says "No"
#### What _should_ have happened?:
donbot recognizes "No" and moves onto next question
#### Steps to reproduce:
Say "No" to military question on donbot
#### Additional info:
 - **Bot Revision**: Found under the hidden folder /.git/packed-refs, which you open with notepad and copy the second line of text to paste here.
 - **Anything else you may wish to add**: (Related issues, console output, error notices, screenshots, etc.)

**Comment by SpadesNeil** [comment]
Does this _only_ happen with the Don Bot?

**Comment by NicksAccount** [comment]
I believe it's also on the cheryl bot, cause i do remember this happening before

**Comment by SpadesNeil** [comment]
I can't reliably reproduce this. Send me info about calls where this happens.

**Comment by SpadesNeil** [comment]
Listened to a call where it did this and I am convinced what actually happened is the speech reco either choked out for a moment, or "No" came out as something unrecognized. Either way, closing this as invalid.
