### ISSUE TITLE
no should not be caught during call start

### ISSUE THREAD

**Issue by tylrewirth** [LCN-Dev/GoogleBot#254]
#### Brief description of the issue:
If the first thing said when the call opens is "no" by the customer the Don bot replies with uncooperative rebuttal. 
#### What happened?:
When the call started the customer said hello and speech read 'no'. Don bot then replied with uncooperative rebuttal.
#### What _should_ have happened?:
The rebuttal should not have been called.
#### Steps to reproduce:
Say 'no' when the call is started.
#### Additional info:
 - **Bot Revision**: (Check the version of the bot posted, located in the title bar, or copy the commit URL and paste it here.) Revenge of the Don Bot Fri 05/19/29.19
 - **Anything else you may wish to add**: (Related issues, console output, error notices, screenshots, etc.)

**Comment by SpadesNeil** [comment]
Found the issue and resolved with https://github.com/LCN-Dev/GoogleBot/pull/238/commits/f54fff50305794982836e8bbe1e9dd4ec9edfcd0
