### ISSUE TITLE
Manual bot doesn't say anything when it dispo's certain calls

### ISSUE THREAD

**Issue by NicksAccount** [LCN-Dev/GoogleBot#263]
#### Brief description of the issue:
On some of the shortcuts for some questions, (for example, "2 - Correct customer unavailable") there is no "Ok, have a good day" or "Alright, thank you" before the call gets hungup. 
#### What happened?:
Call hungup and dispo'd without saying goodbye or something along those lines
#### What _should_ have happened?:
"Alright, thank you." *hangup*
#### Steps to reproduce:
Press 2 on first question on manual bot
#### Additional info:
Not sure if it's cause there wasn't a file or not. But, there is now

**Comment by SpadesNeil** [comment]
Wrong Github.

https://github.com/MTS11648/Don-NonAutomated-Bot

**Comment by NicksAccount** [comment]
Oops! thanks
