### ISSUE TITLE
[state].mp3 coming up as initials, not state's full name

### ISSUE THREAD

**Issue by NicksAccount** [LCN-Dev/GoogleBot#264]
#### Brief description of the issue:
the .mp3 files for the state the bot is looking for are just the initials (IA for Iowa) 
#### What happened?:
Looked for .mp3 for state and could not find the correct clip
#### What _should_ have happened?:
the correct clip should have been found
#### Steps to reproduce:
use manual bot
press 1 and hear it not say the state
in the console window it will show the state as the state's initials 
#### Additional info:
 - **Bot Revision**: (Check the version of the bot posted, located in the title bar, or copy the commit URL and paste it here.)
 - **Anything else you may wish to add**: (Related issues, console output, error notices, screenshots, etc.)

**Comment by SpadesNeil** [comment]
Wrong githuuuuubbbbb. :U

**Comment by SpadesNeil** [comment]
don't feel bad, I have made this error at least several times
