### ISSUE TITLE
Inconsistent Handling of Apostrophes and Capitalization

### ISSUE THREAD

**Issue by SpadesNeil** [LCN-Dev/GoogleBot#49]
#### Brief description of the issue
I see a lot of 'if' statements with things like...
response.Contains("she's not here")
resp.Contains("i'm at work") 

However I also see stuff like
resp.Contains("im good")

This is inconsistent and may be causing issues. At the very least, it's nonsense to have to write code for having and not having correct grammar.

In the speech recognition, I also incorrectly see things capitalized. Example: "Whos LCN" or "I have insurance" while the code says response.Contains("who's LCN") or ("i have insurance"). This is clearly not correct.

#### What you expected to happen
All strings put through the program should be filtered to automatically _remove_ things like apostrophes and capitalization.

#### What actually happened
Supposedly this isn't happening. If it is, then the code needs to be double checked for apostrophes because it could be why certain catches are being ignored.

#### Steps to reproduce
N/A

#### Additional info:
 - **Bot Revision**: https://github.com/LCN-Dev/GoogleBot/commit/840030550712ec3f430af447078b6d5783e8020f

**Comment by SpadesNeil** [comment]
The code where we use the apostrophes is incorrect, and all cases using apostrophes should be fixed.

The speech reco is correctly removing apostrophes. It's some of our code that isn't set correctly.

**Comment by MTS11648** [comment]
You could use "StringComparison.InvariantCultureIgnoreCase" to fix the capitalization issue, I'm not sure what you could do about the apostrophes without manually going through and fixing them.
